version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scx-admin-app
    image: scx-admin-app
    restart: unless-stopped
    ports:
      - '3369:3369'
    environment:
      - NODE_ENV=production
    networks:
      - scx-network

networks:
  scx-network:
    external: true
