version: '3.8'

services:
  app:
    container_name: scx-admin-app
    image: scx-admin:latest
    restart: unless-stopped
    ports:
      - '3369:3369'
    environment:
      - NODE_ENV=production
    networks:
      - scx-network

networks:
  scx-network:
    driver: bridge
